name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # This workflow runs when changes are pushed to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use a Linux environment for the build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Action to checkout your repository code

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Use Node.js version 18

      - name: Install dependencies
        run: npm install # Install your project's npm dependencies

      - name: Build the project
        run: CI=false npm run build # Build your React app (CI=false prevents warnings from failing the build)

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Action to deploy to gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub's built-in token for actions
          publish_dir: ./build # The directory where your built app output is located
